### PR TITLE
Change flag to FLAG_ACTIVITY_NEW_TASK

### LINKED ISSUE #3: Android 5
```
E/RNInvokeApp( 8137): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/RNInvokeApp( 8137):   at android.app.ContextImpl.startActivity(ContextImpl.java:1377)
E/RNInvokeApp( 8137):   at android.app.ContextImpl.startActivity(ContextImpl.java:1357)
E/RNInvokeApp( 8137):   at android.content.ContextWrapper.startActivity(ContextWrapper.java:324)
E/RNInvokeApp( 8137):   at android.content.ContextWrapper.startActivity(ContextWrapper.java:324)
E/RNInvokeApp( 8137):   at com.codegulp.invokeapp.RNInvokeApp.invokeApp(RNInvokeApp.java:55)
E/RNInvokeApp( 8137):   at java.lang.reflect.Method.invoke(Native Method)
E/RNInvokeApp( 8137):   at java.lang.reflect.Method.invoke(Method.java:372)
E/RNInvokeApp( 8137):   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
E/RNInvokeApp( 8137):   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
E/RNInvokeApp( 8137):   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/RNInvokeApp( 8137):   at android.os.Handler.handleCallback(Handler.java:815)
E/RNInvokeApp( 8137):   at android.os.Handler.dispatchMessage(Handler.java:104)
```

Expectation:
Application to open 

Reality: 
Nothing happens and above error can be seen in the `adb logcat`.

Android Version: 5
React Native Version: 0.59

### PR DESCRIPTION
**Pull request by janakact**
Fixed #3
Tested in Android 5 and 7

### CODE REVIEW

**Comment by janakact** [comment]
Even though this worked I am not sure whether this is the correct fix.  ;)

**Comment by tassoruas** [comment]
Hello janakact!
This fixed my problem in Android 5.1.1 too!
Thanks for that.

**Comment by vicke4** [comment]
Hi @janakact,

Thanks for the pull request. I really appreciate it. I'm thinking of leaving the choice of Intent flag to the user with `FLAG_ACTIVITY_SINGLE_TOP` being default. It offers a lot of flexibility.

What do you think?

**Comment by janakact** [comment]
@vicke4 Not so sure about it.

**Comment by Kraudia** [comment]
It resolved my issue related with android 9, thank you! Now app moves to foreground automatically.

**Pull request merged**
